# config/services.yaml

parameters:

services:
    # Configuration du DataSubscriber avec injection du service DataService
    App\EventSubscriber\DataSubscriber:
        arguments:
            $dataService: '@App\Service\DataService'
        tags:
            - { name: 'kernel.event_subscriber' }

    # Configuration pour les services automatiques
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique comme subscriber, command, etc.

    # Services pour les classes situées dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
